CREATE TABLE [dbo].[Goods]
(
	[Id] INT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
	[GoodName] [nvarchar](100) NULL,
	[GoodGroupId] [int] NULL,
	[GoodBrandId] [int] NULL,
	[GoodParametersId] [int] NULL,
	[GoodParametersConfirmed] [bit] NULL,
	[GoodParametersConfirmationDate] [smalldatetime] NULL,
	[GoodWidth] [numeric](10, 2) NULL,
	[GoodHeight] [numeric](10, 2) NULL,
	[GoodVolume] [numeric](5, 4) NULL,
	[GoodWeight] [numeric](10, 2) NULL,
	[GoodBoxQuantity] [int] NULL,
	[GoodBoxWeight] [numeric](10, 2) NULL,
	[GoodPalletQuantity] [int] NULL,
	[GoodLength] [numeric](10, 2) NULL,
	[GoodsParametersConfirmationUserId] [int] NULL,
	[GoodArticle] [nvarchar](20) NULL,
	[GoodGUID] [uniqueidentifier] NULL,
	[NDS] [numeric](10, 2) NULL,
	[Description] [ntext] NULL,
	[IsService] [bit] NOT NULL DEFAULT 0,
	[IsPackage] [bit] NOT NULL DEFAULT 0,
	[IsSerialNumberNeeded] [bit] NULL,
	[RoznCategory] [numeric](2, 0) NULL,
	[GuarantyPeriodDesc] [nvarchar](50) NULL,
	[IsMarked] [bit] NULL,
	[IDRRef] [binary](16) NULL,
	[Podlozhka] [binary](16) NULL,
	[PodlozhkaChanged] [datetime] NULL,
	[Cennik_Template] [int] NULL,
	[CennikStarDate] [datetime] NULL,
	[CennikEndDate] [datetime] NULL,
	[SellersDirectionId] [int] NULL,
	[_Version] [timestamp] NULL,
)
